sudo: false
language: php

script:
  #- ./vendor/bin/phpunit # If you have tests
  - bash ./bin/deploy.sh

env:
  global:
    # - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
    - COMMIT_AUTHOR_EMAIL: waldermort@gmail.com
    - COMMIT_AUTHOR_USERNAME: Travis CI

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - openssl aes-256-cbc -K $encrypted_200beba27379_key -iv $encrypted_200beba27379_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
  # - php: 5.5
  # - php: 5.6
    # env:
    # - EXECUTE_DEPLOYMENT=true
  - php: 7.1.3
  # - php: hhvm
  # allow_failures:
  # - php: hhvm

# before_install:
# - phpenv config-rm xdebug.ini
# - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

# script:
#   - ./vendor/bin/phpunit # If you have tests

notifications:
  email: true
